import "./globals.css";
import type { Metadata } from "next";
import { Inter, Prompt } from "next/font/google";
import Footer from "./components/Footer";
import Header from "./components/Header";
import CartContextProvider from "./context/cartContext";
import '@radix-ui/themes/styles.css';
import { Theme } from "@radix-ui/themes";

const prompt = Prompt({ subsets: ["latin"],  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  title: "FLEXMART",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={prompt.className}>
        <Theme>
        <CartContextProvider>
          <Header />
          {children}
          <Footer />
        </CartContextProvider>
        </Theme>
      </body>
    </html>
  );
}
